---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gke-connect
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: gcr.io/sre-bootcamp-328203/asiaimage
          resources:
            requests:
              cpu: "100m"
          
