
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: gke-connect
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 34.131.83.186
